version: 2

updates:

  #
  # NuGet
  #
  - package-ecosystem: "nuget"
    directory: "/services/AuthService"
    schedule:
      interval: weekly

    labels:
      - dependencies

    open-pull-requests-limit: 10

  #
  # npm
  #
  - package-ecosystem: "npm"
    directory: "/apps/cyber-app"
    schedule:
      interval: weekly

    labels:
      - dependencies

    open-pull-requests-limit: 10

  #
  # GitHub Actions
  #
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly

    labels:
      - github-actions