name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  detect:
    uses: ./.github/workflows/detect-changes.yml

  authservice:
    needs: detect
    if: needs.detect.outputs.authservice == 'true'
    uses: ./.github/workflows/authservice-ci.yml

  cyberapp:
    needs: detect
    if: needs.detect.outputs.frontend == 'true'
    uses: ./.github/workflows/cyberapp-ci.yml